

name: Build-Test-Release

on:
  push:
    tags:
      - 'v*'        # create release when you push a tag like v1.0.0
  workflow_dispatch:

permissions:
  contents: write   # required to create releases

jobs:
  build:
    runs-on: ajul
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & Test
        run: mvn -B -V clean verify

      - name: Upload artifact for release step
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar

  release:
    needs: build
    runs-on: ajul
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: built-jar
          path: dist/

      - name: Create GitHub Release and attach JAR
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_PASSWORD }}
